### ISSUE TITLE
App crashes while emaluating in android studio

### ISSUE THREAD

**Issue by Ammad7** [dvdciri/RSPi2-Home-Domotic-System#1]
Hi , very nice work done by you. can you please help me out i am new in android and pi . when i emulate the application it crashes and give error "reload again" please help me out to figure this out. Thanks.

**Comment by dvdciri** [comment]
Hi, unfortunately this was just a place where I have put some code for an article and I can't give support for any issue that happens with this codebase.
Sorry about that.
